name: GitHub Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore: [.github/**]
  pull_request:
    branches: 
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch: 
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true 

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "triggered by event: ${{ github.event_name }}"
      - name: Debug output of the environment
        run: |
          echo "the selected env is: ${{ github.event.inputs.environment }}"
      - uses: actions/checkout@v3.0.2
      - name: List files in the repository
        run: |
          echo "Listing the files in the repo ${{ github.repository }}"
          tree
          
  Production-deployment:
    runs-on: ubuntu-latest
    ## needs: [Test, Load-Test] ## this would introduce a depends-on those jobs
    environment:
      name: Production
      url: https://wheretodeployit
    if: github.event.inputs.environment == 'Production'
    steps:
      - run: echo "deploying to prod now!"

